"""
Legal Grounding Layer  --  ILLUSTRATIVE SCAFFOLD ONLY.

Wraps examples/audit_demo.py with a retrieval layer that attaches statute
citations to every classification produced by the financial audit.

DESIGN CONSTRAINT (hard-enforced in code):
    Every cited legal source carries a `verbatim_excerpt` field. In a
    production deployment this MUST contain text returned by the RAG
    retriever -- never text generated by the LLM. In this demo every
    excerpt defaults to PLACEHOLDER. The report renders [UNVERIFIED]
    next to every placeholder and a final BLOCKING_VERIFICATION_ERROR
    counter so the report cannot be silently treated as authoritative.

    To go to production: replace `LEGAL_CORPUS` entries' `verbatim_excerpt`
    with output from your RAG retriever (FAISS / pgvector / etc.). The
    report renderer and tier logic are unchanged.

STRUCTURED LEGAL SIGNAL:
    `LegalSource.taxable_event` is the structured tri-state signal used by the
    conflict detector. `holding_summary` is a paraphrase intended for human
    display; it is NOT used as authority and is NOT scanned for keywords.
    `verbatim_excerpt` (when populated by a real RAG retriever) is the only
    text treated as authoritative.

Confidence tiers used in this layer:
    CONFIRMED      -- enacted, in-force law or final administrative ruling
    DRAFT          -- bill text introduced; not yet enacted
    PROPOSED       -- discussion document, no bill yet (e.g., Treasury notice)
    INTERPRETATION -- general principle applied to facts lacking direct
                      digital-asset authority

NOT TAX OR LEGAL ADVICE.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from audit_demo import (  # noqa: E402
    WALLET,
    build_dataframe,
    consistency_checks,
    run_pipeline,
)

PLACEHOLDER = "[PLACEHOLDER -- supply retrieved RAG chunk verbatim before issuing report]"


# ---------------------------------------------------------------------------
# 1. Legal corpus -- replace verbatim_excerpt with retriever output in prod
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class LegalSource:
    id: str
    jurisdiction: str  # "US-FED", "EU", "PL", "INTL"
    kind: str  # "STATUTE" | "IRS_NOTICE" | "REV_RUL" | "REG"
    # | "DRAFT" | "INTERPRETATION"
    tier: str  # "CONFIRMED" | "DRAFT" | "PROPOSED"
    # | "INTERPRETATION"
    effective_date: str | None
    title: str
    holding_summary: str  # neutral one-line summary, NOT a citation
    verbatim_excerpt: str  # MUST come from retriever; placeholder by default
    source_url: str
    applies_to: tuple[str, ...]  # categories from audit_demo.classify()
    taxable_event: bool | None = None  # True/False = explicit; None = silent


LEGAL_CORPUS: list[LegalSource] = [
    LegalSource(
        id="US-NOTICE-2014-21",
        jurisdiction="US-FED",
        kind="IRS_NOTICE",
        tier="CONFIRMED",
        effective_date="2014-04-14",
        title="IRS Notice 2014-21  -- Virtual currency treated as property",
        holding_summary=(
            "Convertible virtual currency is treated as "
            "property for US federal tax purposes; general "
            "property tax principles apply."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://www.irs.gov/pub/irs-drop/n-14-21.pdf",
        applies_to=("Swap (capital event)", "External acquisition (basis seeded)"),
        taxable_event=True,
    ),
    LegalSource(
        id="US-REV-RUL-2019-24",
        jurisdiction="US-FED",
        kind="REV_RUL",
        tier="CONFIRMED",
        effective_date="2019-10-09",
        title="Rev. Rul. 2019-24  -- Hard forks and airdrops",
        holding_summary=(
            "Taxpayer recognizes ordinary income equal to FMV "
            "of cryptocurrency received in an airdrop following "
            "a hard fork, in the year dominion and control is "
            "established."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://www.irs.gov/pub/irs-drop/rr-19-24.pdf",
        applies_to=("Airdrop (ordinary income)",),
        taxable_event=True,
    ),
    LegalSource(
        id="US-REV-RUL-2023-14",
        jurisdiction="US-FED",
        kind="REV_RUL",
        tier="CONFIRMED",
        effective_date="2023-08-01",
        title="Rev. Rul. 2023-14  -- Staking rewards",
        holding_summary=(
            "Cash-method taxpayer must include FMV of "
            "validation rewards in gross income in the taxable "
            "year in which the taxpayer obtains dominion and "
            "control."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://www.irs.gov/pub/irs-drop/rr-23-14.pdf",
        applies_to=("Staking income (ordinary)",),
        taxable_event=True,
    ),
    LegalSource(
        id="US-IRC-1091",
        jurisdiction="US-FED",
        kind="STATUTE",
        tier="CONFIRMED",
        effective_date="1954-08-16",
        title="26 U.S.C. sec.1091  -- Wash sales of stock or securities",
        holding_summary=(
            "Wash-sale disallowance applies to 'stock or "
            "securities'. Digital assets are NOT currently "
            "within scope under existing Treasury/IRS "
            "interpretation; tax-loss harvesting on crypto "
            "remains permissible under current law."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://www.law.cornell.edu/uscode/text/26/1091",
        applies_to=("Swap (capital event)",),
        taxable_event=True,
    ),
    LegalSource(
        id="US-PROPOSAL-1091-DIGITAL-EXT",
        jurisdiction="US-FED",
        kind="DRAFT",
        tier="DRAFT",
        effective_date=None,
        title=(
            "Proposed legislative extension of IRC sec.1091 wash-sale "
            "rule to digital assets (multiple bills across recent "
            "Congresses)"
        ),
        holding_summary=(
            "Recurring proposals would bring digital assets "
            "within sec.1091. NOT enacted as of corpus "
            "snapshot. Strategic implication: tax-loss "
            "harvesting remains permissible TODAY but the "
            "30-day repurchase window may become disallowed."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="(supply current bill citation from RAG)",
        applies_to=("Swap (capital event)",),
        taxable_event=True,
    ),
    LegalSource(
        id="US-FORM-1099-DA",
        jurisdiction="US-FED",
        kind="REG",
        tier="CONFIRMED",
        effective_date="2025-01-01",
        title=(
            "Treas. Reg. on Form 1099-DA broker reporting  -- centralized "
            "digital-asset brokers (DeFi broker rule rescinded by "
            "Congressional Review Act in 2025)"
        ),
        holding_summary=(
            "Centralized digital-asset brokers must report "
            "gross proceeds from 2025 transactions on Form "
            "1099-DA. The DeFi broker rule was rescinded; "
            "self-custodial on-chain DEX activity is NOT "
            "subject to broker reporting today."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="(supply final reg citation from RAG)",
        applies_to=("Swap (capital event)", "External acquisition (basis seeded)"),
        taxable_event=True,
    ),
    LegalSource(
        id="EU-MICA-2023-1114",
        jurisdiction="EU",
        kind="REG",
        tier="CONFIRMED",
        effective_date="2024-12-30",
        title="Regulation (EU) 2023/1114 (MiCA)  -- Markets in Crypto-Assets",
        holding_summary=(
            "MiCA establishes prudential and disclosure rules "
            "for crypto-asset issuers and CASPs across the EU. "
            "It does NOT itself impose income-tax "
            "characterization, which remains a Member-State "
            "competence."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://eur-lex.europa.eu/eli/reg/2023/1114/oj",
        applies_to=(
            "External acquisition (basis seeded)",
            "Inbound deposit -- UNKNOWN BASIS",
            "Internal transfer (non-taxable)",
        ),
        taxable_event=None,
    ),
    LegalSource(
        id="INTL-OECD-CARF-2022",
        jurisdiction="INTL",
        kind="REG",
        tier="CONFIRMED",
        effective_date="2026-01-01",
        title=(
            "OECD Crypto-Asset Reporting Framework (CARF), 2022, plus "
            "DAC8 transposition in EU Member States"
        ),
        holding_summary=(
            "CARF imposes automatic exchange of crypto-asset "
            "user information by reporting CASPs (first "
            "exchanges in many adopters from 2027 covering "
            "2026 data). Self-custodial wallet activity is "
            "NOT itself reportable, but interactions with "
            "reporting CASPs WILL be visible to the user's "
            "tax authority."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="https://www.oecd.org/tax/exchange-of-tax-information/",
        applies_to=("External acquisition (basis seeded)", "Inbound deposit -- UNKNOWN BASIS"),
        taxable_event=None,
    ),
    LegalSource(
        id="PL-PIT-ART-30B-1A",
        jurisdiction="PL",
        kind="STATUTE",
        tier="CONFIRMED",
        effective_date="2019-01-01",
        title=(
            "Ustawa o PIT, Art. 30b ust. 1a  -- 19% PIT on gains from "
            "disposal of cryptoassets for fiat or goods/services"
        ),
        holding_summary=(
            "Polish PIT residents recognize 19% income tax on "
            "the difference between proceeds from disposal of "
            "cryptoassets (for fiat / goods / services / "
            "settlement of liabilities) and documented "
            "acquisition costs. Crypto-to-crypto swaps are "
            "NOT a taxable event under the current statutory "
            "text."
        ),
        verbatim_excerpt=PLACEHOLDER,
        source_url="(supply current consolidated text citation)",
        applies_to=("Swap (capital event)",),
        taxable_event=False,
    ),
    LegalSource(
        id="US-INTERP-INTERNAL-TRANSFER",
        jurisdiction="US-FED",
        kind="INTERPRETATION",
        tier="INTERPRETATION",
        effective_date=None,
        title=("Interpretive: same-beneficial-owner wallet transfer is not a realization event"),
        holding_summary=(
            "Movement of digital assets between two wallets "
            "controlled by the same taxpayer is not a sale or "
            "exchange and does not give rise to gain or loss. "
            "Anchored in IRC sec.1001 realization principles; "
            "no digital-asset-specific ruling on point. "
            "Document beneficial ownership and basis "
            "carryover."
        ),
        verbatim_excerpt=(
            "INTERPRETATION  -- no quoted statute. Anchor "
            "principle: IRC sec.1001(a) defines gain/loss as "
            "arising from sale or other disposition of "
            "property; same-owner transfer is neither."
        ),
        source_url="(no direct authority; interpretive)",
        applies_to=("Internal transfer (non-taxable)",),
        taxable_event=False,
    ),
    LegalSource(
        id="US-INTERP-FAILED-TX-FEE",
        jurisdiction="US-FED",
        kind="INTERPRETATION",
        tier="INTERPRETATION",
        effective_date=None,
        title=("Interpretive: deductibility of network fees on failed transactions"),
        holding_summary=(
            "No published guidance specifically addresses "
            "network fees on failed on-chain transactions. "
            "Possible treatments: (i) added to basis of "
            "intended acquisition (n/a if no acquisition), "
            "(ii) ordinary loss under IRC sec.165, or "
            "(iii) personal non-deductible expense. Position "
            "should be disclosed if material."
        ),
        verbatim_excerpt=(
            "INTERPRETATION  -- no quoted statute. No digital-asset-specific authority on point."
        ),
        source_url="(no direct authority; interpretive)",
        applies_to=("Failed transaction",),
        taxable_event=None,
    ),
    LegalSource(
        id="US-INTERP-MISSING-BASIS",
        jurisdiction="US-FED",
        kind="INTERPRETATION",
        tier="INTERPRETATION",
        effective_date=None,
        title=("Interpretive: zero-basis fallback when acquisition data cannot be substantiated"),
        holding_summary=(
            "Where the taxpayer cannot substantiate basis, "
            "the IRS position has historically been to treat "
            "basis as zero on disposal (Cohan rule may permit "
            "estimation in some circumstances). Resolve "
            "before filing to avoid inflated gain."
        ),
        verbatim_excerpt=(
            "INTERPRETATION  -- general substantiation "
            "principles; no digital-asset-specific ruling."
        ),
        source_url="(no direct authority; interpretive)",
        applies_to=("Inbound deposit -- UNKNOWN BASIS",),
        taxable_event=None,
    ),
]


# ---------------------------------------------------------------------------
# 2. Retrieval (stand-in for vector search; replace with embeddings in prod)
# ---------------------------------------------------------------------------
def retrieve(category: str, jurisdictions: tuple[str, ...]) -> list[LegalSource]:
    """Category + jurisdiction filter. In prod this becomes a vector lookup
    keyed on (category description, jurisdiction) returning top-k chunks."""
    return [s for s in LEGAL_CORPUS if category in s.applies_to and s.jurisdiction in jurisdictions]


# ---------------------------------------------------------------------------
# 3. Verification gate -- prevents silent reliance on placeholder text
# ---------------------------------------------------------------------------
def count_unverified(sources: list[LegalSource]) -> int:
    return sum(1 for s in sources if s.verbatim_excerpt == PLACEHOLDER)


# ---------------------------------------------------------------------------
# 4. Report renderer
# ---------------------------------------------------------------------------
PRIMARY_JURISDICTION = "US-FED"
SECONDARY_JURISDICTIONS: tuple[str, ...] = ("EU", "PL", "INTL")


def _fmt_source(s: LegalSource, role: str) -> list[str]:
    flag = "  [UNVERIFIED]" if s.verbatim_excerpt == PLACEHOLDER else ""
    eff = f"effective {s.effective_date}" if s.effective_date else "not enacted"
    return [
        f"      [{s.tier} | {role} | {s.jurisdiction} | {eff}]{flag}",
        f"      ID:       {s.id}",
        f"      Title:    {s.title}",
        f"      Summary:  {s.holding_summary}",
        f"      Source:   {s.source_url}",
        f"      Excerpt:  {s.verbatim_excerpt}",
    ]


def render_legal_report(
    financial_audit: pd.DataFrame, findings: list[dict], checks: list[str]
) -> str:
    sep = "=" * 78
    sub = "-" * 78

    lines: list[str] = []
    lines += [
        sep,
        "LEGAL FOUNDATIONS & AUDIT REPORT  --  ILLUSTRATIVE",
        f"Wallet:                {WALLET}",
        "Period:                2024-12-15 -> 2025-05-03 (synthetic)",
        f"Primary jurisdiction:  {PRIMARY_JURISDICTION}",
        f"Secondary corpora:     {', '.join(SECONDARY_JURISDICTIONS)}",
        "Cost-basis method:     FIFO, single-wallet view",
        sep,
        "",
    ]

    by_cat: dict[str, list[pd.Series]] = defaultdict(list)
    for _, row in financial_audit.iterrows():
        by_cat[row["category"]].append(row)

    total_income = financial_audit["income_usd"].sum()
    total_gain = financial_audit["gain_usd"].sum()
    total_fee = financial_audit["fee_usd"].sum()

    grey_cats = [
        c
        for c in by_cat
        if not any(s.tier == "CONFIRMED" for s in retrieve(c, (PRIMARY_JURISDICTION,)))
    ]

    all_cited: list[LegalSource] = []
    for c in by_cat:
        all_cited.extend(retrieve(c, (PRIMARY_JURISDICTION,) + SECONDARY_JURISDICTIONS))
    unverified = count_unverified(all_cited)

    # ----- Executive legal summary -----
    lines += [
        "EXECUTIVE LEGAL SUMMARY",
        sub,
        f"  Categories observed:                  {len(by_cat)}",
        f"  Categories with CONFIRMED authority:  {len(by_cat) - len(grey_cats)} / {len(by_cat)}",
        "  Grey-area categories (no CONFIRMED authority in primary jurisdiction):",
    ]
    if grey_cats:
        for c in grey_cats:
            lines.append(f"      - {c}")
    else:
        lines.append("      (none)")
    lines += [
        f"  Ordinary income recognized:           $ {total_income:>12}",
        f"  Net realized capital gain / (loss):   $ {total_gain:>12}",
        f"  Network fees paid by wallet:          $ {total_fee:>12}",
        f"  Internal-consistency checks:          "
        f"{'PASS' if not checks else 'FAIL (' + str(len(checks)) + ')'}",
        "",
        "  BLOCKING_VERIFICATION_GATE:",
        f"      Unverified citations (placeholder excerpts): {unverified}",
        ("      ==> Report is NOT issuable as authoritative until the RAG"),
        ("          retriever populates verbatim_excerpt for every cited source."),
        "",
    ]

    # ----- Per-category itemization -----
    lines += ["DETAILED FINDINGS BY CATEGORY", sub]
    for cat in sorted(by_cat):
        rows = by_cat[cat]
        sigs = ", ".join(r["signature"] for r in rows)
        cat_income = sum((Decimal(str(r["income_usd"])) for r in rows), Decimal("0"))
        cat_gain = sum((Decimal(str(r["gain_usd"])) for r in rows), Decimal("0"))
        primary_sources = retrieve(cat, (PRIMARY_JURISDICTION,))
        secondary_sources = retrieve(cat, SECONDARY_JURISDICTIONS)

        lines += [
            "",
            f"  CATEGORY: {cat}",
            f"  Affected signatures: {sigs}",
            f"  Income recognized:   $ {cat_income}",
            f"  Gain recognized:     $ {cat_gain}",
            "",
        ]
        if not primary_sources and not secondary_sources:
            lines.append("    [GREY AREA] No corpus snippet matched. Manual review required.")
            continue

        if primary_sources:
            lines.append("    Primary-jurisdiction authority:")
            for s in primary_sources:
                lines += _fmt_source(s, role="PRIMARY")
        else:
            lines.append(
                "    [GREY AREA] No primary-jurisdiction "
                "authority returned. Classification rests on "
                "interpretation only."
            )

        if secondary_sources:
            lines += ["", "    Secondary-jurisdiction context (informational):"]
            for s in secondary_sources:
                lines += _fmt_source(s, role="SECONDARY")

        # Conflict surfacing
        for s_sec in secondary_sources:
            for s_pri in primary_sources:
                if s_pri.jurisdiction == s_sec.jurisdiction:
                    continue
                if s_pri.taxable_event is None or s_sec.taxable_event is None:
                    continue
                if s_pri.taxable_event != s_sec.taxable_event:
                    pri_label = "taxable" if s_pri.taxable_event else "non-taxable"
                    sec_label = "taxable" if s_sec.taxable_event else "non-taxable"
                    lines += [
                        "",
                        (
                            f"    [CONFLICT] {s_pri.jurisdiction} treats this category as "
                            f"{pri_label}; {s_sec.jurisdiction} treats it as {sec_label}. "
                            f"Resolution depends on taxpayer's tax residence and treaty position."
                        ),
                    ]
                    break

    # ----- Risk findings carried over from financial layer -----
    lines += ["", "FINANCIAL-LAYER RISK FINDINGS (forwarded)", sub]
    if not findings:
        lines.append("  (none)")
    for f in findings:
        lines.append(f"  - {f}")

    # ----- Strategic recommendations driven by DRAFT corpus entries -----
    drafts = [s for s in LEGAL_CORPUS if s.tier in {"DRAFT", "PROPOSED"}]
    upcoming = [
        s
        for s in LEGAL_CORPUS
        if s.tier == "CONFIRMED" and s.effective_date and s.effective_date > "2025-12-31"
    ]

    lines += ["", "STRATEGIC RECOMMENDATIONS", sub]
    lines.append("  [Driven by DRAFT / PROPOSED entries in corpus]")
    if not drafts:
        lines.append("    (no DRAFT or PROPOSED entries in current corpus)")
    for s in drafts:
        flag = "  [UNVERIFIED]" if s.verbatim_excerpt == PLACEHOLDER else ""
        lines += [
            f"    - {s.id} ({s.tier}){flag}",
            f"        {s.holding_summary}",
            "        Action: re-run this report when the bill text is "
            "finalized; the harvest-and-repurchase posture currently "
            "permitted by US-IRC-1091 may be disallowed.",
        ]

    lines.append("")
    lines.append("  [Driven by CONFIRMED entries with future effective dates]")
    if not upcoming:
        lines.append("    (none)")
    for s in upcoming:
        flag = "  [UNVERIFIED]" if s.verbatim_excerpt == PLACEHOLDER else ""
        lines += [
            f"    - {s.id} (CONFIRMED, effective {s.effective_date}){flag}",
            f"        {s.holding_summary}",
            "        Action: confirm whether any CASP counterparty in "
            "this audit becomes an in-scope reporter under the cited "
            "regulation; reconcile to user's CRS/CARF disclosures.",
        ]

    lines += [
        "",
        "  [Operational, derived from this report]",
        "    - Resolve all 'Inbound deposit -- UNKNOWN BASIS' rows "
        "before filing; the zero-basis fallback (US-INTERP-MISSING-"
        "BASIS) inflates future gain on disposal.",
        "    - Document beneficial ownership of OWN_WALLET_2 to "
        "preserve the non-realization position under "
        "US-INTERP-INTERNAL-TRANSFER.",
        "    - Disclose the failed-transaction fee position "
        "(US-INTERP-FAILED-TX-FEE) on the return if material.",
        "",
    ]

    lines += [
        sep,
        "ILLUSTRATIVE OUTPUT  --  NOT TAX OR LEGAL ADVICE.",
        "Verbatim excerpts marked [UNVERIFIED] are placeholders;",
        "this report is NOT authoritative until they are populated",
        "from a real RAG retriever.",
        sep,
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 5. Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    df = build_dataframe()
    classified, _ledger, findings = run_pipeline(df)
    checks = consistency_checks(classified, _ledger)
    print(render_legal_report(classified, findings, checks))


if __name__ == "__main__":
    main()
